# Generated by Django 3.0.6 on 2020-05-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(default=1988, max_length=2083),
            preserve_default=False,
        ),
    ]
